name: Build & Test (.NET Framework 4.7.2)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages for solution
      run: nuget restore SatiDotNet2.sln   

    - name: Build solution
      run: msbuild SatiDotNet2.sln /p:Configuration=Release

    - name: Run xUnit tests
      run: |
        cd .. & vstest.console.exe "SatiDotNet2Tests\bin\Release\SatiDotNet2Tests.dll" & cd SatiDotNet2
